import { useState } from 'react';
import { PiggyBank, Plus, Trash2, User, Target, Pencil, CheckCircle, History, Dices, Users, Trophy } from 'lucide-react';
import { formatMoney } from '../lib/format.js';

const Savings = ({ jars, onAdd, onEdit, onDeposit, onDelete, onHistory, onOpenRoulette, onComplete }) => {
  const [viewCompleted, setViewCompleted] = useState(false);
  const [viewType, setViewType] = useState('shared'); 
  const filterJars = (status) => jars.filter(j => { const jStatus = j.status || 'active'; const isStatusMatch = status === 'completed' ? jStatus === 'completed' : jStatus !== 'completed'; const jOwner = j.owner || 'shared'; let isOwnerMatch = false; if (viewType === 'shared') { isOwnerMatch = jOwner === 'shared'; } else { isOwnerMatch = jOwner !== 'shared'; } return isStatusMatch && isOwnerMatch; }).sort((a, b) => { if (status === 'completed') { return (b.completedAt?.seconds || 0) - (a.completedAt?.seconds || 0); } return (a.createdAt?.seconds || 0) - (b.createdAt?.seconds || 0); });
  const displayJars = filterJars(viewCompleted ? 'completed' : 'active');

  return (
    <div className="space-y-6 animate-[fadeIn_0.5s_ease-out]">
        <div className="flex justify-between items-center px-2"><h2 className="font-bold text-xl text-gray-800">{viewCompleted ? '🏆 榮譽殿堂' : '🎯 存錢目標'}</h2><div className="flex gap-2"><button onClick={() => setViewCompleted(!viewCompleted)} className={`px-3 py-2 rounded-xl shadow-xs text-xs font-bold flex items-center gap-1.5 transition-all ${viewCompleted ? 'bg-gray-800 text-surface' : 'bg-surface text-gray-500 border border-gray-100 hover:bg-gray-50'}`}>{viewCompleted ? <Target size={14}/> : <Trophy size={14}/>}{viewCompleted ? '返回目標' : '已完成'}</button></div></div>
        <div className="bg-gray-100 p-1 rounded-xl flex"><button onClick={() => setViewType('shared')} className={`flex-1 py-2 rounded-lg text-sm font-bold flex items-center justify-center gap-2 transition-all ${viewType === 'shared' ? 'bg-surface text-gray-800 shadow-xs' : 'text-gray-400 hover:text-gray-600'}`}><Users size={16}/> 共同</button><button onClick={() => setViewType('personal')} className={`flex-1 py-2 rounded-lg text-sm font-bold flex items-center justify-center gap-2 transition-all ${viewType === 'personal' ? 'bg-surface text-gray-800 shadow-xs' : 'text-gray-400 hover:text-gray-600'}`}><User size={16}/> 個人</button></div>
        {!viewCompleted && (<div className="flex gap-2"><button onClick={onOpenRoulette} className="flex-1 bg-surface text-purple-600 p-3 rounded-xl shadow-xs border border-purple-100 active:scale-95 transition-transform flex items-center justify-center gap-2 text-sm font-bold"><Dices size={18} /> 命運轉盤</button><button onClick={onAdd} className="flex-1 bg-gray-900 text-surface p-3 rounded-xl shadow-lg active:scale-95 transition-transform flex items-center justify-center gap-2 text-sm font-bold"><Plus size={18} /> 新增目標</button></div>)}
        <div className="space-y-4">
            {displayJars.length === 0 ? (<div className="flex flex-col items-center justify-center py-16 text-gray-400 gap-3">{viewCompleted ? <Trophy size={48} className="opacity-20" /> : <PiggyBank size={48} className="opacity-20" />}<span className="text-sm">{viewCompleted ? `還沒有${viewType === 'shared' ? '共同' : '個人'}完成的目標，加油！` : `還沒有${viewType === 'shared' ? '共同' : '個人'}存錢計畫，快來建立一個！`}</span></div>) : (displayJars.map(jar => {
                    const cur = Number(jar.currentAmount) || 0; const tgt = Number(jar.targetAmount) || 1; const progress = Math.min((cur / tgt) * 100, 100); const isAchieved = cur >= tgt; const isPersonal = jar.owner && jar.owner !== 'shared';
                    if (!viewCompleted) {
                        return (
                            <div key={jar.id} className="bg-surface p-5 rounded-3xl shadow-xs border border-gray-100 relative overflow-hidden group flex flex-col">
                                <div className="flex justify-between items-start mb-4 relative z-10"><div><div className="flex items-center gap-2"><h3 className="font-bold text-lg text-gray-800 flex items-center gap-2">{jar.name}<button onClick={() => onEdit(jar)} className="text-gray-300 hover:text-blue-500"><Pencil size={14}/></button></h3>{isPersonal && (<span className={`text-[10px] px-2 py-0.5 rounded-full font-bold ${jar.owner === 'bf' ? 'bg-blue-100 text-blue-600' : 'bg-pink-100 text-pink-600'}`}>{jar.owner === 'bf' ? '👦 男友' : '👧 女友'}</span>)}</div><div className="text-xs text-gray-400 mt-1">目標 {formatMoney(tgt)}</div></div><div className={`font-bold px-3 py-1 rounded-full text-xs flex items-center gap-1 ${isAchieved ? 'bg-green-100 text-green-700' : 'bg-yellow-100 text-yellow-700'}`}>{isAchieved ? <CheckCircle size={12}/> : <Target size={12}/>} {Math.round(progress)}%</div></div>
                                <div className="mb-4 relative z-10"><div className="text-3xl font-black text-gray-800 mb-1">{formatMoney(cur)}</div><div className="w-full bg-gray-100 h-3 rounded-full overflow-hidden"><div className={`h-full transition-all duration-1000 ${isAchieved ? 'bg-green-500' : 'bg-linear-to-r from-yellow-300 to-orange-400'}`} style={{ width: `${progress}%` }}></div></div></div>
                                <div className="flex justify-between items-center relative z-10 mb-4"><div className="flex gap-2">{!isPersonal && (<><div className="flex items-center gap-1 bg-blue-50 text-blue-600 px-2 py-1 rounded-lg text-xs font-bold" title="男友貢獻"><span>👦</span><span>{formatMoney(jar.contributions?.bf || 0)}</span></div><div className="flex items-center gap-1 bg-pink-50 text-pink-600 px-2 py-1 rounded-lg text-xs font-bold" title="女友貢獻"><span>👧</span><span>{formatMoney(jar.contributions?.gf || 0)}</span></div></>)}</div><div className="flex gap-2 ml-auto"><button onClick={() => onHistory(jar)} className="p-2 bg-gray-100 text-gray-500 rounded-lg hover:bg-gray-200"><History size={18}/></button><button onClick={() => onDelete(jar.id)} className="p-2 text-gray-300 hover:text-red-400"><Trash2 size={18}/></button><button onClick={() => onDeposit(jar.id)} className="bg-gray-900 text-surface px-4 py-2 rounded-xl text-sm font-bold shadow-md active:scale-95 transition-transform">存錢</button></div></div>
                                <button disabled={!isAchieved} onClick={() => onComplete(jar)} className={`w-full mt-auto py-3 rounded-xl font-bold text-sm flex items-center justify-center gap-2 transition-all ${isAchieved ? 'bg-linear-to-r from-yellow-400 to-orange-500 text-surface shadow-lg shadow-orange-200 active:scale-95 animate-pulse' : 'bg-gray-100 text-gray-300 cursor-not-allowed border border-gray-200'}`}>{isAchieved ? <><Trophy size={16}/> 達成目標！點擊完成</> : '尚未達成目標'}</button>
                                <PiggyBank className="absolute -bottom-4 -right-4 text-gray-50 opacity-50 z-0 transform -rotate-12" size={120} />
                            </div>
                        );
                    } else {
                        const date = jar.completedAt ? new Date(jar.completedAt.seconds * 1000).toLocaleDateString() : '未知日期';
                        return (
                            <div key={jar.id} className="bg-yellow-50/50 border border-yellow-100 p-5 rounded-3xl relative overflow-hidden group">
                                <div className="flex justify-between items-start relative z-10"><div><div className="flex items-center gap-2 mb-1"><h3 className="font-bold text-lg text-gray-800">{jar.name}</h3>{isPersonal && (<span className={`text-[10px] px-2 py-0.5 rounded-full font-bold ${jar.owner === 'bf' ? 'bg-blue-100 text-blue-600' : 'bg-pink-100 text-pink-600'}`}>{jar.owner === 'bf' ? '👦 男友' : '👧 女友'}</span>)}</div><div className="flex gap-2"><span className="bg-yellow-100 text-yellow-700 text-[10px] font-bold px-2 py-0.5 rounded-full">已完成</span><span className="text-xs text-gray-400 flex items-center">達成日期: {date}</span></div></div><Trophy className="text-yellow-400" size={24} /></div>
                                <div className="mt-4 flex items-end gap-2"><div className="text-3xl font-black text-gray-800">{formatMoney(jar.currentAmount)}</div><div className="text-xs text-gray-400 mb-1.5 font-bold">/ 目標 {formatMoney(jar.targetAmount)}</div></div>
                                <div className="mt-4 pt-3 border-t border-yellow-100 flex justify-between items-center"><div className="flex gap-2">{!isPersonal && (<><div className="flex items-center gap-1 text-xs font-bold text-blue-400"><span>👦</span><span>{formatMoney(jar.contributions?.bf || 0)}</span></div><div className="flex items-center gap-1 text-xs font-bold text-pink-400"><span>👧</span><span>{formatMoney(jar.contributions?.gf || 0)}</span></div></>)}</div><div className="flex gap-2 ml-auto"><button onClick={() => onHistory(jar)} className="p-2 bg-surface text-gray-400 rounded-lg hover:text-gray-600 shadow-xs"><History size={16}/></button><button onClick={() => onDelete(jar.id)} className="p-2 bg-surface text-gray-300 hover:text-red-400 rounded-lg shadow-xs"><Trash2 size={16}/></button></div></div>
                            </div>
                        );
                    }
                }))}
        </div>
    </div>
  );
};

export default Savings;
